# Generated by Django 4.2.1 on 2024-11-12 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_names', models.CharField(max_length=255, null=True)),
                ('image_actors', models.URLField(blank=True, null=True)),
                ('descrip_actors', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.actors')),
            ],
            options={
                'verbose_name': 'MovieActor',
                'verbose_name_plural': 'MovieActors',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('rating2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('movie_actors', models.ManyToManyField(related_name='movies', through='film.MovieActor', to='film.actors')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['?'],
            },
        ),
        migrations.AddField(
            model_name='movieactor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movies'),
        ),
        migrations.AlterUniqueTogether(
            name='movieactor',
            unique_together={('movie', 'actor')},
        ),
    ]
