# Generated by Django 4.2.1 on 2024-11-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_movies_rating_userprofile_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
