# Generated by Django 4.2.1 on 2024-07-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_movie_duration_movie_rating_movie_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
