# Generated by Django 4.2.1 on 2024-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_count',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
