# Generated by Django 4.2.1 on 2024-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_rating_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
