# Generated by Django 4.2.1 on 2024-11-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_rating_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review_count',
        ),
    ]
