# Generated by Django 4.2.1 on 2024-07-02 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating2',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
