# Generated by Django 4.2.1 on 2024-12-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_remove_rating_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='review_count',
        ),
    ]
