# Generated by Django 4.2.1 on 2024-07-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_movie_rating2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating2',
        ),
    ]
