# Generated by Django 4.2.1 on 2024-07-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_film_delete_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Movie',
        ),
    ]
